### ISSUE TITLE
'No class provided' error

### ISSUE THREAD

**Issue by gglusman** [mulinlab/vSampler#5]
I'm getting the following error:

```
% java -jar -Xms1g -Xmx4g VariantSampler-1.0.2.jar Sampler -Q:vcf example.vcf -D panels/EUR.gz | more
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mulinlab.variantsampler.cmdline.JarCommadLine.processAllCommandLinePrograms(JarCommadLine.java:96)
	at org.mulinlab.variantsampler.cmdline.JarCommadLine.extractCommandLineProgram(JarCommadLine.java:53)
	at org.mulinlab.variantsampler.cmdline.JarCommadLine.instanceMain(JarCommadLine.java:40)
	at org.mulinlab.variantsampler.cmdline.JarCommadLine.main(JarCommadLine.java:36)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
	at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
	at org.broadinstitute.barclay.argparser.ClassFinder.<clinit>(ClassFinder.java:29)
	... 4 more

```

How should I fix? Thanks!

**Comment by Npaffen** [comment]
I face the same error.
